import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import apicore from "./docs/api_core_v1/sidebar";
import apiemissions from "./docs/api_emissions_v1/sidebar";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //apisidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
    apisidebar: [{
      type: "category",
      label: "Core",
      link: {
        type: "generated-index",
        title: "NDD Elog Core API",
        // description:
        //   "This is a sample server Petstore server in OpenAPI 3.1. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/coreapi",
      },
      items: apicore,
    },
    {
      type: "category",
      label: "Emissões",
      link: {
        type: "generated-index",
        title: "NDD Elog Emissões API",
        slug: "/category/emissionsapi",
      },
      items: apiemissions,
    }
  ]
};

export default sidebars;
