import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-v1/nddelog-core-service-api",
    },
    {
      type: "category",
      label: "Entrega",
      link: {
        type: "generated-index",
        title: "Entrega",
        slug: "/category/api-v1/entrega",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/listagem-de-comprovantes-e-ocorrencias-de-entrega",
          label: "Listagem de comprovantes e ocorrências de entrega",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Fatura",
      link: {
        type: "generated-index",
        title: "Fatura",
        slug: "/category/api-v1/fatura",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/listagem-de-faturas",
          label: "Listagem de faturas",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Filial",
      link: {
        type: "generated-index",
        title: "Filial",
        slug: "/category/api-v1/filial",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/listagem-de-filiais",
          label: "Listagem de filiais",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/criacao-de-uma-nova-filial",
          label: "Criação de uma nova filial",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/busca-filial-atraves-do-identificador",
          label: "Busca filial através do identificador",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/remove-filial-atraves-do-identificador",
          label: "Remove filial através do identificador",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-uma-filial-atraves-do-identificador",
          label: "Edição parcial de uma filial através do identificador",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Motorista",
      link: {
        type: "generated-index",
        title: "Motorista",
        slug: "/category/api-v1/motorista",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/listagem-de-motoristas",
          label: "Listagem de motoristas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/criacao-de-um-novo-motorista",
          label: "Criação de um novo motorista",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/busca-motorista-atraves-do-identificador",
          label: "Busca motorista através do identificador",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-um-motorista-atraves-do-identificador",
          label: "Edição parcial de um motorista através do identificador",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-v1/remove-motorista-atraves-do-identificador",
          label: "Remove motorista através do identificador",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Prestador",
      link: {
        type: "generated-index",
        title: "Prestador",
        slug: "/category/api-v1/prestador",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/criacao-de-um-novo-prestador",
          label: "Criação de um novo prestador",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/listagem-de-prestadores",
          label: "Listagem de prestadores",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/busca-prestador-atraves-do-identificador",
          label: "Busca prestador através do identificador",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/remove-prestador-atraves-do-identificador",
          label: "Remove prestador através do identificador",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-um-prestador-atraves-do-identificador",
          label: "Edição parcial de um prestador através do identificador",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Proprietario",
      link: {
        type: "generated-index",
        title: "Proprietario",
        slug: "/category/api-v1/proprietario",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/remove-proprietario-atraves-do-identificador",
          label: "Remove proprietário através do identificador",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-v1/busca-proprietario-atraves-do-identificador",
          label: "Busca proprietário através do identificador",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/listagem-de-proprietarios",
          label: "Listagem de proprietários",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/criacao-de-um-novo-proprietario",
          label: "Criação de um novo proprietário",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-um-proprietario-atraves-do-identificador",
          label: "Edição parcial de um proprietário através do identificador",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Veiculo",
      link: {
        type: "generated-index",
        title: "Veiculo",
        slug: "/category/api-v1/veiculo",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/listagem-de-veiculos",
          label: "Listagem de veículos",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/criacao-de-um-novo-veiculo",
          label: "Criação de um novo veículo",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/busca-veiculo-atraves-do-identificador",
          label: "Busca veiculo através do identificador",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-v1/remove-veiculo-atraves-do-identificador",
          label: "Remove veículo através do identificador",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-um-veiculo-atraves-do-identificador",
          label: "Edição parcial de um veículo através do identificador",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Viagem",
      link: {
        type: "generated-index",
        title: "Viagem",
        slug: "/category/api-v1/viagem",
      },
      items: [
        {
          type: "doc",
          id: "api-v1/criacao-de-um-nova-viagem",
          label: "Criação de um nova viagem",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-v1/cancela-uma-viagem-atraves-do-identificador",
          label: "Cancela uma viagem através do identificador",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-v1/edicao-parcial-de-uma-viagem-atraves-do-identificador",
          label: "Edição parcial de uma viagem através do identificador",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api-v1/schemas/atualizarcondutor",
          label: "AtualizarCondutor",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/atualizarfilial",
          label: "AtualizarFilial",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/atualizarprestador",
          label: "AtualizarPrestador",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/atualizarproprietario",
          label: "AtualizarProprietario",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/atualizarveiculo",
          label: "AtualizarVeiculo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/atualizarviagem",
          label: "AtualizarViagem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/bankdatacommand",
          label: "BankDataCommand",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/bodyworktype",
          label: "BodyworkType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/branchviewmodel",
          label: "BranchViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarcomponentefrete",
          label: "CriarComponenteFrete",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarcondutor",
          label: "CriarCondutor",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criardocumentoviagem",
          label: "CriarDocumentoViagem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarfilial",
          label: "CriarFilial",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarlocal",
          label: "CriarLocal",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarparada",
          label: "CriarParada",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarpedagio",
          label: "CriarPedagio",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarprestador",
          label: "CriarPrestador",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarproprietario",
          label: "CriarProprietario",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarroteirizacao",
          label: "CriarRoteirizacao",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarveiculo",
          label: "CriarVeiculo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/criarviagem",
          label: "CriarViagem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/dadosbancarios",
          label: "DadosBancarios",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/deliveryviewmodel",
          label: "DeliveryViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/driverviewmodel",
          label: "DriverViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/exceptionpayload",
          label: "ExceptionPayload",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/freightpaymentmethod",
          label: "FreightPaymentMethod",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/freightreceipttype",
          label: "FreightReceiptType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/invoiceviewmodel",
          label: "InvoiceViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-branchviewmodel",
          label: "ODataValue`1.BranchViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-driverviewmodel",
          label: "ODataValue`1.DriverViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-branchviewmodel",
          label: "ODataValue`1.List`1.BranchViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-deliveryviewmodel",
          label: "ODataValue`1.List`1.DeliveryViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-driverviewmodel",
          label: "ODataValue`1.List`1.DriverViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-invoiceviewmodel",
          label: "ODataValue`1.List`1.InvoiceViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-ownerviewmodel",
          label: "ODataValue`1.List`1.OwnerViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/odatavalue-1-list-1-providerviewmodel",
          label: "ODataValue`1.List`1.ProviderViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/ownerviewmodel",
          label: "OwnerViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/providerviewmodel",
          label: "ProviderViewModel",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/relashionshipdatadto-1-criarcondutor",
          label: "RelashionshipDataDto`1.CriarCondutor",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/relashionshipdatadto-1-criarfilial",
          label: "RelashionshipDataDto`1.CriarFilial",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/relashionshipdatadto-1-criarprestador",
          label: "RelashionshipDataDto`1.CriarPrestador",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/relashionshipdatadto-1-criarproprietario",
          label: "RelashionshipDataDto`1.CriarProprietario",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/relashionshipdatadto-1-criarveiculo",
          label: "RelashionshipDataDto`1.CriarVeiculo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/rotatedtype",
          label: "RotatedType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/routedefinitiontype",
          label: "RouteDefinitionType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/routetype",
          label: "RouteType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/severity",
          label: "Severity",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/tollcategory",
          label: "TollCategory",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/tollreceipttype",
          label: "TollReceiptType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/tolltagsupplier",
          label: "TollTagSupplier",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/traveldocumenttype",
          label: "TravelDocumentType",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/typedocument",
          label: "TypeDocument",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/typenotification",
          label: "TypeNotification",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/validationfailure",
          label: "ValidationFailure",
          className: "schema",
        },
        {
          type: "doc",
          id: "api-v1/schemas/vehicletype",
          label: "VehicleType",
          className: "schema",
        },
      ],
    },
  ],
};

//export default sidebar.apisidebar;
export default sidebar;
